### ISSUE TITLE
Bug on the back-end for the search feature

### ISSUE THREAD

**Issue by mathieuabeille** [feedback-news/feedback-main#235] opened 2021-01-11 09:55 UTC
**Step to reproduce**
Step 1: Launch the webapp
Step 2: Launch several times different searches on the landing page (ie "Trump", "Trum", "Trump ")
For some of them, the output will be:
![image](https://user-images.githubusercontent.com/29702932/104166628-5ef5dd00-53fb-11eb-8dbd-ee599498f577.png)

**Investigation**
The bug should come from the back-end. Indeed, when we are requesting the API endpoint for search from the console thanks to a Curl, sometime the output is an empty array `[]`.

**Comment by Ledoux** [comment] 2021-01-14 22:49
I cannot reproduce this bug, if that so... it seems to be more related to the different web instances on scalingo we had at that time last week . Each time we do a requets : we are answered by one round-robined instance of them (there are 5 of them) , and apparelty one of them at least was kind of no giving data.
Maybe because of a postgres connection that was broken for it.

Now all the web instances are rebooted and all seems to work, so this bug disappear, we can close this ticket.

**Closed by Ledoux** 2021-01-14 22:49 UTC
